"""qsvt_store_campaign.py — produce QSVT solutions in the qtrk_store, mirroring
the fixed-epsilon 1BQF (quantum) campaign of Verify_new_results.

For every fixed-eps quantum solve ON DISK (gamma in {1,2,3}, hit_ineff in
{0, 0.01}, n_trk 10..400, 3 reps -> 108 solves), this script:

  1. regenerates the event + Hamiltonian (same event_key / ham_key),
  2. runs qp.solve_qsvt (gamma-aware degree-40 LINE-COMB inverse: narrow
     1/lambda passes at the four P4 true-track eigenvalue lines only;
     matrix-free statevector semantics — the exact circuit output),
  3. stores the raw solution under a solver='qsvt' sol_key,
  4. appends the solver='qsvt' rows to manifest/solutions.csv (dedup),
  5. rebuilds the Verify_new_results metrics rows and MERGES them into
     manifest/metrics.csv (other studies' rows untouched; .bak kept).

Spectral bounds are computed per solve from the coupling spectral radius:
spec(A) = s - spec(C), rho(C) from a fast Lanczos 'LA' on C (C >= 0, the
Perron root dominates).  If s +/- rho exceeds the default design window
(s +/- 3.8) the polynomial is refit on the wider domain for that solve.

NOTE: manifest/solutions.csv is REGENERATED by qp.build_manifest from the
study specs — a manifest rebuild from specs will drop the qsvt rows (the
solutions .npz files stay; re-run this script to re-register them).

Usage:  Q_env python qsvt_store_campaign.py [--dry-run]
"""
from __future__ import annotations

import argparse
import shutil
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
import scipy.sparse as sp
from scipy.sparse.linalg import eigsh

for _p in ("/data/bfys/gscriven/Quantum_Track_Reconstruction/Toy_Characterisation/_shared",
           "/data/bfys/gscriven/LHCb_VeLo_Toy_Model/src"):
    if _p not in sys.path:
        sys.path.insert(0, _p)
import os
os.environ.setdefault("QTRK_STORE", "/data/bfys/gscriven/qtrk_store")
import qtrk_pipeline as qp  # noqa: E402

EPS_FIXED = 0.002
STUDY = "Verify_new_results"
DEGREE = 40
PAD = 0.10


def spectral_bounds_for(ham) -> tuple[float, float]:
    """spec(A) = s - spec(C); rho(C) via fast Lanczos on the coupling."""
    s = float(getattr(ham, "gamma", 3.0)) + float(getattr(ham, "delta", 1.0))
    n = ham.A.shape[0]
    C = (s * sp.identity(n, format="csr") - ham.A.tocsr())
    if n <= 256:
        w = np.linalg.eigvalsh(C.toarray())
        rho = float(max(abs(w[0]), abs(w[-1])))
    else:
        try:
            # C is symmetric non-negative, so (Perron-Frobenius) the spectral
            # radius IS lambda_max: one fast Lanczos 'LA' suffices.
            rho = float(eigsh(C, k=1, which="LA",
                              return_eigenvectors=False, maxiter=3000)[0])
        except Exception:
            d = np.asarray(abs(C).sum(axis=1)).ravel()
            rho = float(d.max())  # Gershgorin on C
    return s - rho - PAD, s + rho + PAD


def main(dry_run: bool = False, overwrite: bool = False) -> int:
    md = qp.manifest_dir()
    sols = pd.read_csv(md / "solutions.csv")
    fx = sols[(sols.eps_provenance == "set") &
              (sols.epsilon.round(6) == EPS_FIXED) &
              (sols.solver == "quantum")]
    fx = fx[fx.sol_key.map(qp.solution_exists)].reset_index(drop=True)
    print(f"[campaign] mirroring {len(fx)} fixed-eps quantum solves as solver='qsvt'")

    new_rows, done, t00 = [], 0, time.time()
    for i, r in fx.iterrows():
        key = qp.sol_key(r.event_key, r.ham_key, "qsvt", readout="statevector")
        row = dict(r)
        row.update(sol_key=key, solver="qsvt", device="na",
                   readout="statevector", shots=0)
        new_rows.append(row)
        if qp.solution_exists(key) and not overwrite:
            done += 1
            continue
        if dry_run:
            continue
        t0 = time.time()
        ev = qp.ensure_event(n_trk=int(r.n_trk), rep=int(r.rep),
                             sigma_scatt=float(r.sigma_scatt),
                             sigma_res=float(r.sigma_res),
                             phi_max=float(r.phi_max),
                             hit_ineff=float(r.hit_ineff))[0]
        ham = qp.build_hamiltonian(ev, epsilon=float(r.epsilon),
                                   kernel=str(r.kernel),
                                   gamma=float(r.gamma), delta=float(r.delta))
        truth = np.asarray(qp.truth_from_event(ev), bool)
        lo, hi = spectral_bounds_for(ham)
        s = float(r.gamma) + float(r.delta)
        dom = None
        if lo < s - 3.8 or hi > s + 3.8:           # rare: widen the design window
            half = max(s - lo, hi - s)
            dom = (s - half, s + half)
        res = qp.solve_qsvt(ham, degree=DEGREE, spectral_bounds=(lo, hi), domain=dom)
        qp.save_solution(
            key, res["sol"], event_key_=r.event_key, ham_key_=r.ham_key,
            solver="qsvt", n_seg=int(ham.n_segments), n_true=int(truth.sum()),
            overwrite=overwrite,
            P_anc=res["P_anc"], n_sys=res["n_sys"], n_qubits=res["n_qubits"],
            degree=res["degree"], filter_design=res["filter_design"], t_solve=res["t_solve"],
            A_nnz=int(ham.A.nnz), epsilon=float(r.epsilon), kernel=str(r.kernel),
            gamma=float(r.gamma), delta=float(r.delta))
        done += 1
        print(f"  [{done:3d}/{len(fx)}] g={r.gamma:.0f} drop={r.hit_ineff:.2f} "
              f"T={int(r.n_trk):4d} rep={int(r.rep)}  n={ham.n_segments:6d}  "
              f"P_succ={res['P_anc']:.4f}  q={res['n_qubits']}  "
              f"{time.time()-t0:5.1f}s", flush=True)

    # ---- register in solutions.csv (dedup on sol_key) ----------------------
    if not dry_run and new_rows:
        nr = pd.DataFrame(new_rows)
        merged = pd.concat([sols, nr], ignore_index=True)
        merged = merged.drop_duplicates(subset="sol_key", keep="first")
        shutil.copy(md / "solutions.csv", md / "solutions.csv.bak")
        merged.to_csv(md / "solutions.csv", index=False)
        print(f"[campaign] solutions.csv: {len(sols)} -> {len(merged)} rows "
              f"(+{len(merged)-len(sols)} qsvt)")

    # ---- rebuild metrics for this study, merge into metrics.csv ------------
    if not dry_run:
        from qtrk_pipeline import build_metrics as bm
        df_new = bm.build(STUDY)
        mpath = md / "metrics.csv"
        old = pd.read_csv(mpath)
        keep = old[old.study != STUDY]
        out = pd.concat([keep, df_new], ignore_index=True)
        shutil.copy(mpath, md / "metrics.csv.bak")
        out.to_csv(mpath, index=False)
        by = df_new.groupby("solver").size().to_dict()
        print(f"[campaign] metrics.csv: {len(old)} -> {len(out)} rows; "
              f"{STUDY} by solver: {by}")
    print(f"[campaign] total {time.time()-t00:.0f}s")
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--overwrite", action="store_true",
                    help="re-solve and replace existing qsvt solutions")
    a = ap.parse_args()
    raise SystemExit(main(a.dry_run, a.overwrite))
