"""qsvt_densify_campaign.py — densify the paper figures' data, by the standard
store protocols (direct row construction as in qsvt_robustness_campaign.py;
sol_key dedup; solutions.csv/.bak; per-study metrics merge; phases SERIALIZED).

Phase A (headline curves, Verify_new_results):
  - NEW T points {30, 75, 150, 300, 550} filling the log-T axis,
    gamma in {1,2,3} x drop in {0, 0.01}, reps: 10 (T<=300) / 5 (T=550),
    solvers: classical + qsvt (both ~seconds per solve).
  - TOP-UP existing gamma=3 points (both drops): qsvt reps -> 10 at
    T in {10,20,50,100,200,400} and -> 5 at {700,1000}; classical partners
    solved wherever missing.

Phase C (noise curves, QSVT_robustness):
  - NEW configs sigma_scatt {2e-4,4e-4,6e-4}, sigma_res {0.0025,0.0075},
    drop {0.005, 0.03}; x T {100,400}; reps 0-4. Existing 9 configs topped
    up from 3 -> 5 reps. classical + qsvt.

Phase B (1BQF top-up, the expensive tail — runs LAST):
  - gamma=3, both drops: T {10,20,30,50,75} -> 10 reps; T {100,150,200} -> 5.
    (T>=300 untouched: statevector cost explodes, 261 s @400 ... 6.6 h @700.)

NOTE: solutions.csv is regenerated by qp.build_manifest from specs — a rebuild
drops these rows (npz survive; re-run this script to re-register).
Usage: Q_env python qsvt_densify_campaign.py [--dry-run] [--phases ACB]
"""
from __future__ import annotations

import argparse
import shutil
import sys
import time

import numpy as np
import pandas as pd
import scipy.sparse as sp
from scipy.sparse.linalg import eigsh

for _p in ("/data/bfys/gscriven/Quantum_Track_Reconstruction/Toy_Characterisation/_shared",
           "/data/bfys/gscriven/LHCb_VeLo_Toy_Model/src"):
    if _p not in sys.path:
        sys.path.insert(0, _p)
import os
os.environ.setdefault("QTRK_STORE", "/data/bfys/gscriven/qtrk_store")
import qtrk_pipeline as qp  # noqa: E402

EPS, DELTA, DEGREE, PAD = 0.002, 1.0, 40, 0.10
BASE_NOISE = dict(sigma_scatt=1e-4, sigma_res=0.0)


def spectral_bounds_for(ham, s):
    n = ham.A.shape[0]
    C = (s * sp.identity(n, format="csr") - ham.A.tocsr())
    try:
        rho = float(eigsh(C, k=1, which="LA", return_eigenvectors=False,
                          maxiter=3000, tol=1e-4)[0])
    except Exception:
        rho = float(np.asarray(abs(C).sum(axis=1)).ravel().max())
    return s - rho - PAD, s + rho + PAD


def solve_point(rows, *, study, T, rep, gamma, hit_ineff, sigma_scatt, sigma_res,
                do_classical=True, do_qsvt=True, do_quantum=False, dry=False):
    """One (event, gamma) point: register + solve missing solvers."""
    s = gamma + DELTA
    ev, ekey = qp.ensure_event(n_trk=T, rep=rep, sigma_scatt=sigma_scatt,
                               sigma_res=sigma_res, phi_max=0.2,
                               hit_ineff=hit_ineff)
    hkey = qp.ham_key(epsilon=EPS, kernel="step", gamma=gamma, delta=DELTA,
                      eps_provenance="set")
    common = dict(event_key=ekey, ham_key=hkey, study=study, studies=study,
                  n_trk=T, rep=rep, sigma_scatt=sigma_scatt, sigma_res=sigma_res,
                  phi_max=0.2, hit_ineff=hit_ineff, ghost_rate=0.0,
                  epsilon=EPS, eps_provenance="set", kernel="step",
                  erf_sigma=0.0, gamma=gamma, delta=DELTA, shots=0)
    kC = qp.sol_key(ekey, hkey, "classical")
    kQ = qp.sol_key(ekey, hkey, "qsvt", readout="statevector")
    k1 = qp.sol_key(ekey, hkey, "quantum", device="CPU", readout="statevector")
    need_C = do_classical and not qp.solution_exists(kC)
    need_Q = do_qsvt and not qp.solution_exists(kQ)
    need_1 = do_quantum and not qp.solution_exists(k1)
    if do_classical:
        rows.append(dict(common, sol_key=kC, solver="classical", device="na", readout="na"))
    if do_qsvt:
        rows.append(dict(common, sol_key=kQ, solver="qsvt", device="na", readout="statevector"))
    if do_quantum:
        rows.append(dict(common, sol_key=k1, solver="quantum", device="CPU", readout="statevector"))
    if dry or not (need_C or need_Q or need_1):
        return need_C or need_Q or need_1, 0.0
    t0 = time.time()
    ham = qp.build_hamiltonian(ev, epsilon=EPS, kernel="step", gamma=gamma, delta=DELTA)
    truth = np.asarray(qp.truth_from_event(ev), bool)
    meta = dict(epsilon=EPS, kernel="step", gamma=gamma, delta=DELTA,
                A_nnz=int(ham.A.nnz))
    if need_C:
        solC, tC = qp.solve_classical(ham)
        qp.save_solution(kC, solC, event_key_=ekey, ham_key_=hkey, solver="classical",
                         n_seg=int(ham.n_segments), n_true=int(truth.sum()),
                         t_solve=tC, **meta)
    if need_Q:
        lo, hi = spectral_bounds_for(ham, s)
        dom = None
        if lo < s - 3.8 or hi > s + 3.8:
            half = max(s - lo, hi - s) + 0.5
            dom = (s - half, s + half)
        res = qp.solve_qsvt(ham, degree=DEGREE, spectral_bounds=(lo, hi), domain=dom)
        qp.save_solution(kQ, res["sol"], event_key_=ekey, ham_key_=hkey, solver="qsvt",
                         n_seg=int(ham.n_segments), n_true=int(truth.sum()),
                         P_anc=res["P_anc"], n_sys=res["n_sys"],
                         n_qubits=res["n_qubits"], degree=res["degree"],
                         filter_design=res["filter_design"], t_solve=res["t_solve"], **meta)
    if need_1:
        res = qp.solve_quantum(ham, device="CPU", readout="statevector")
        qp.save_solution(k1, res["sol"], event_key_=ekey, ham_key_=hkey, solver="quantum",
                         n_seg=int(ham.n_segments), n_true=int(truth.sum()),
                         P_anc=res["P_anc"], n_sys=res["n_sys"],
                         n_qubits=res["n_qubits"], t_solve=res["t_solve"], **meta)
    return True, time.time() - t0


def flush(rows, studies):
    """Register rows (dedup) and merge-rebuild metrics for the given studies."""
    md = qp.manifest_dir()
    sols = pd.read_csv(md / "solutions.csv")
    nr = pd.DataFrame(rows)
    merged = pd.concat([sols, nr], ignore_index=True).drop_duplicates(
        subset="sol_key", keep="first")
    shutil.copy(md / "solutions.csv", md / "solutions.csv.bak")
    merged.to_csv(md / "solutions.csv", index=False)
    print(f"[densify] solutions.csv: {len(sols)} -> {len(merged)} rows", flush=True)
    from qtrk_pipeline import build_metrics as bm
    mpath = md / "metrics.csv"
    for study in studies:
        df_new = bm.build(study)
        old = pd.read_csv(mpath)
        out = pd.concat([old[old.study != study], df_new], ignore_index=True)
        shutil.copy(mpath, md / "metrics.csv.bak")
        out.to_csv(mpath, index=False)
        print(f"[densify] metrics[{study}]: {len(old)} -> {len(out)} rows; "
              f"{df_new.groupby('solver').size().to_dict()}", flush=True)


def phase_A(rows, dry):
    NEW_T = [(30, 10), (75, 10), (150, 10), (300, 10), (550, 5)]
    TOPUP_T = [(10, 10), (20, 10), (50, 10), (100, 10), (200, 10), (400, 10),
               (700, 5), (1000, 5)]
    n = 0
    t0 = time.time()
    # new T points: all gammas, both drops
    for T, nrep in NEW_T:
        for drop in (0.0, 0.01):
            for rep in range(nrep):
                for gamma in (3.0, 1.0, 2.0):
                    did, dt = solve_point(rows, study="Verify_new_results", T=T,
                                          rep=rep, gamma=gamma, hit_ineff=drop,
                                          dry=dry, **BASE_NOISE)
                    n += 1
                if rep == 0 or T >= 300:
                    print(f"  [A] T={T} drop={drop} rep={rep} done ({time.time()-t0:.0f}s)", flush=True)
    # top-up existing gamma=3 (both drops), classical+qsvt only
    for T, nrep in TOPUP_T:
        for drop in (0.0, 0.01):
            for rep in range(nrep):
                solve_point(rows, study="Verify_new_results", T=T, rep=rep,
                            gamma=3.0, hit_ineff=drop, dry=dry, **BASE_NOISE)
        print(f"  [A-topup] T={T} done ({time.time()-t0:.0f}s)", flush=True)
    print(f"[phase A] done in {time.time()-t0:.0f}s", flush=True)


def phase_C(rows, dry):
    CONFIGS = [dict(BASE_NOISE, hit_ineff=0.0)]
    for ss in (1e-4, 2e-4, 3e-4, 4e-4, 5e-4, 6e-4, 8e-4):
        CONFIGS.append(dict(sigma_scatt=ss, sigma_res=0.0, hit_ineff=0.0))
    for sr in (0.0025, 0.005, 0.0075, 0.01):
        CONFIGS.append(dict(sigma_scatt=1e-4, sigma_res=sr, hit_ineff=0.0))
    for hi in (0.005, 0.01, 0.02, 0.03, 0.05):
        CONFIGS.append(dict(sigma_scatt=1e-4, sigma_res=0.0, hit_ineff=hi))
    # dedup configs
    seen, cfgs = set(), []
    for c in CONFIGS:
        k = (c["sigma_scatt"], c["sigma_res"], c["hit_ineff"])
        if k not in seen:
            seen.add(k); cfgs.append(c)
    t0 = time.time()
    for cfg in cfgs:
        for T in (100, 400):
            for rep in range(5):
                solve_point(rows, study="QSVT_robustness", T=T, rep=rep,
                            gamma=3.0, hit_ineff=cfg["hit_ineff"],
                            sigma_scatt=cfg["sigma_scatt"],
                            sigma_res=cfg["sigma_res"], dry=dry)
        print(f"  [C] ss={cfg['sigma_scatt']:.1e} sr={cfg['sigma_res']:.4f} "
              f"drop={cfg['hit_ineff']:.3f} done ({time.time()-t0:.0f}s)", flush=True)
    print(f"[phase C] done in {time.time()-t0:.0f}s", flush=True)


def phase_B(rows, dry):
    PLAN = [(10, 10), (20, 10), (30, 10), (50, 10), (75, 10),
            (100, 5), (150, 5), (200, 5)]
    t0 = time.time()
    for T, nrep in PLAN:
        for drop in (0.0, 0.01):
            for rep in range(nrep):
                did, dt = solve_point(rows, study="Verify_new_results", T=T,
                                      rep=rep, gamma=3.0, hit_ineff=drop,
                                      do_classical=True, do_qsvt=False,
                                      do_quantum=True, dry=dry, **BASE_NOISE)
                if did and dt > 1:
                    print(f"  [B] 1BQF T={T} drop={drop} rep={rep}: {dt:.0f}s "
                          f"({time.time()-t0:.0f}s total)", flush=True)
            # incremental flush per (T, drop) block: a mid-phase death (the
            # long statevector solves have been OOM-killed twice) then loses
            # at most the in-flight solve, never the registration.
            if rows and not dry:
                flush(rows, ["Verify_new_results"])
                rows.clear()
    print(f"[phase B] done in {time.time()-t0:.0f}s", flush=True)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--phases", default="ACB", help="subset/order of phases, e.g. AC")
    ap.add_argument("--register-only", action="store_true",
                    help="build + flush manifest rows for existing .npz only; never solve")
    a = ap.parse_args()
    if a.register_only:
        # monkey-patch the solvers out: rows are appended regardless, solves skipped
        import qtrk_pipeline as _qp
        _orig_exists = _qp.solution_exists
        # claim everything exists so no solver path is entered
        _qp.solution_exists = lambda k: True
        # ... but only FLUSH rows whose npz actually exists on disk
        _orig_flush = flush

        def _filtered_flush(rows, studies):
            kept = [r for r in rows if _orig_exists(r["sol_key"])]
            print(f"[register-only] {len(kept)}/{len(rows)} planned rows have npz on disk",
                  flush=True)
            if kept:
                # build_metrics also consults solution_exists — give it the real one
                _qp.solution_exists = _orig_exists
                try:
                    _orig_flush(kept, studies)
                finally:
                    _qp.solution_exists = lambda k: True
        globals()["flush"] = _filtered_flush
    rows = []
    studies = set()
    for ph in a.phases:
        if ph == "A":
            phase_A(rows, a.dry_run); studies.add("Verify_new_results")
        elif ph == "C":
            phase_C(rows, a.dry_run); studies.add("QSVT_robustness")
        elif ph == "B":
            phase_B(rows, a.dry_run); studies.add("Verify_new_results")
        # flush after each phase so partial progress is registered
        if rows and not a.dry_run:
            flush(rows, sorted(studies))
            rows = []
    if a.dry_run:
        print(f"[dry-run] would register {len(rows)} rows")
